### ISSUE TITLE
Facebook social media 

### ISSUE THREAD

**Issue by moodydeel900** [LG125YT/Hummus.py#1]

**Comment by LG125YT** [comment]
Elaborate please? This package wasn’t made with social media in mind, its for bot creation on a website by Ziad87. Also, this repo is very outdated, I recommend you check out the (still somewhat outdated) [gitlab repository](https://gitlab.com/lg125yt/hummus.py) or the [package page on PyPI](https://pypi.org/project/hummus2016.py/)
